name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env: 
          FIREBASE_TOKEN: ${{"1//01rUawlTb9cCvCgYIARAAGAESNwF-L9IrN9_ZDbPMgviBJJ1fpLBxZr4Cxuni3kFyx3O8eg8YWvGzKp6BWLNmyB_HkoqA69ek-BI" }}  # Pass secret to Firebase CLI
        run: firebase deploy --only hosting
