name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ 1//016ZTneDIpH2qCgYIARAAGAESNwF-L9IryN-z1D-1taqXFsnNCW-B4hGI6zpPEfoO8x7-GqxJp9ZRYlpaspLGNludPGkSfTD7QHA
 }}
        run: firebase deploy --only hosting
